ALTER TABLE `dbsistemavenda`.`tbproduto` 
DROP COLUMN `QuantidadeEstoque`,
DROP COLUMN `PrecoVenda`,
DROP COLUMN `PrecoCompra`,
ADD COLUMN `marca` VARCHAR(60) NULL AFTER `nome`,
ADD COLUMN `peso` DECIMAL(10,2) NULL AFTER `marca`,
ADD COLUMN `preco_unitario` DECIMAL(10,2) NULL AFTER `peso`,
ADD COLUMN `unidade` VARCHAR(45) NULL AFTER `preco_unitario`,
ADD COLUMN `quantidade` DECIMAL(10,2) NULL AFTER `unidade`,
ADD COLUMN `estoque` INT NULL AFTER `quantidade`,
ADD COLUMN `quantidade_unidade_conversao1` DECIMAL(10,2) NULL AFTER `estoque`,
ADD COLUMN `unidade_conversao1` VARCHAR(45) NULL AFTER `quantidade_unidade_conversao1`,
ADD COLUMN `equivale_quantidade_unidade_conversao1` DECIMAL(10,2) NULL AFTER `unidade_conversao1`,
ADD COLUMN `equivale_unidade_conversao1` VARCHAR(45) NULL AFTER `equivale_quantidade_unidade_conversao1`,
ADD COLUMN `quantidade_unidade_conversao2` DECIMAL(10,2) NULL AFTER `equivale_unidade_conversao1`,
ADD COLUMN `unidade_conversao2` VARCHAR(45) NULL AFTER `quantidade_unidade_conversao2`,
ADD COLUMN `equivale_quantidade_unidade_conversao2` DECIMAL(10,2) NULL AFTER `unidade_conversao2`,
ADD COLUMN `equivale_unidade_conversao2` VARCHAR(45) NULL AFTER `equivale_quantidade_unidade_conversao2`,
CHANGE COLUMN `Nome` `nome` VARCHAR(100) NOT NULL ;
